export default {
	'Hanging Knee Raises': { bodyParts: ['abs'], aerobic: false },
	'Hanging Knee Side Raises': { bodyParts: ['abs'], aerobic: false },
	Plank: { bodyParts: ['abs'], aerobic: false },
	'Mountain Climbers': { bodyParts: ['abs'], aerobic: false },
	'Hip Raises': { bodyParts: ['abs'], aerobic: false },
	Bicycles: { bodyParts: ['abs'], aerobic: false },
	'V Ups': { bodyParts: ['abs'], aerobic: false },
	'Leg Raises': { bodyParts: ['abs'], aerobic: false },
	'Flutter Kicks': { bodyParts: ['abs'], aerobic: false },
	Crunches: { bodyParts: ['abs'], aerobic: false },
	'Sit Ups': { bodyParts: ['abs'], aerobic: false },
	'Windshield Wipers': { bodyParts: ['abs'], aerobic: false },
	'Plank Side Hold': { bodyParts: ['abs'], aerobic: false },
	'Push Ups': { bodyParts: ['chest'], aerobic: false },
	'Incline Push Ups': { bodyParts: ['chest'], aerobic: false },
	'Decline Push Ups': { bodyParts: ['chest'], aerobic: false },
	Dips: { bodyParts: ['chest', 'triceps'], aerobic: false },
	'Low Plank to High Plank': { bodyParts: ['chest', 'triceps'], aerobic: false },
	'Explosive Knee Push Ups': { bodyParts: ['chest'], aerobic: false },
	'Shoulder to Shoulder': { bodyParts: ['chest', 'shoulders'], aerobic: false },
	'Diamond Push Ups': { bodyParts: ['chest', 'triceps'], aerobic: false },
	'Spiderman Pushups': { bodyParts: ['chest'], aerobic: false },
	'Pull Ups': { bodyParts: ['back'], aerobic: false },
	'Wide Grip Pull Ups': { bodyParts: ['back'], aerobic: false },
	'Side to Side Wide Grip Pull Ups': { bodyParts: ['back'], aerobic: false },
	'Chin Ups': { bodyParts: ['back', 'biceps'], aerobic: false },
	'Neutral Grip Pull Ups': { bodyParts: ['back'], aerobic: false },
	Hang: { bodyParts: ['back'], aerobic: false },
	'Scapula Pull Ups': { bodyParts: ['back'], aerobic: false },
	Squats: { bodyParts: ['legs'], aerobic: true },
	'Walking Lunges': { bodyParts: ['legs'], aerobic: true },
	'Forward Lunges': { bodyParts: ['legs'], aerobic: true },
	'Side Lunges': { bodyParts: ['legs'], aerobic: true },
	'Sumo Squats': { bodyParts: ['legs'], aerobic: true },
	'One Legged Squats': { bodyParts: ['legs'], aerobic: true },
	'Deadmill Runs': { bodyParts: ['legs'], aerobic: true },
	'Jump Squats': { bodyParts: ['legs'], aerobic: true },
	'Jumping Lunges': { bodyParts: ['legs'], aerobic: true },
	'Wall Sit': { bodyParts: ['legs'], aerobic: false },
	'Hamstring Hip Raise': { bodyParts: ['legs'], aerobic: false },
	'Handstand Push Ups': { bodyParts: ['shoulders'], aerobic: false },
	'Handstand Hold': { bodyParts: ['shoulders'], aerobic: false },
	'Shoulder Push Ups': { bodyParts: ['shoulders'], aerobic: false },
	'Arm Circles': { bodyParts: ['shoulders'], aerobic: false },
	'On The Wall': { bodyParts: ['shoulders'], aerobic: false },
	'Elbows In Push Ups': { bodyParts: ['triceps', 'chest'], aerobic: false },
	Burpees: { bodyParts: ['full'], aerobic: true },
	'Jumping Jacks': { bodyParts: ['full'], aerobic: true },
	'In And Outs': { bodyParts: ['full'], aerobic: true },
	'Jump Rope': { bodyParts: ['full'], aerobic: true },
	'Broad Jumps': { bodyParts: ['full'], aerobic: true },
};
