import Equipment from './equipment';
import BodyParts from './bodyParts';

export default {
	'Hanging Knee Raises': { bodyParts: [BodyParts.Abs], aerobic: false, equipment: [Equipment.PullUpBar] },
	'Hanging Knee Side Raises': { bodyParts: [BodyParts.Abs], aerobic: false, equipment: [Equipment.PullUpBar] },
	Plank: { bodyParts: [BodyParts.Abs], aerobic: false },
	'Mountain Climbers': { bodyParts: [BodyParts.Abs], aerobic: false },
	'Hip Raises': { bodyParts: [BodyParts.Abs], aerobic: false },
	Bicycles: { bodyParts: [BodyParts.Abs], aerobic: false },
	'V Ups': { bodyParts: [BodyParts.Abs], aerobic: false },
	'Leg Raises': { bodyParts: [BodyParts.Abs], aerobic: false },
	'Flutter Kicks': { bodyParts: [BodyParts.Abs], aerobic: false },
	Crunches: { bodyParts: [BodyParts.Abs], aerobic: false },
	'Sit Ups': { bodyParts: [BodyParts.Abs], aerobic: false },
	'Windshield Wipers': { bodyParts: [BodyParts.Abs], aerobic: false },
	'Plank Side Hold': { bodyParts: [BodyParts.Abs], aerobic: false },
	'Push Ups': { bodyParts: [BodyParts.Chest], aerobic: false },
	'Incline Push Ups': { bodyParts: [BodyParts.Chest], aerobic: false },
	'Decline Push Ups': { bodyParts: [BodyParts.Chest], aerobic: false },
	Dips: { bodyParts: [BodyParts.Chest, BodyParts.Triceps], aerobic: false, equipment: [Equipment.DipBars] },
	'Low Plank to High Plank': { bodyParts: [BodyParts.Chest, BodyParts.Triceps], aerobic: false },
	'Explosive Knee Push Ups': { bodyParts: [BodyParts.Chest], aerobic: false },
	'Shoulder to Shoulder': { bodyParts: [BodyParts.Chest, BodyParts.Shoulders], aerobic: false },
	'Diamond Push Ups': { bodyParts: [BodyParts.Chest, BodyParts.Triceps], aerobic: false },
	'Spiderman Pushups': { bodyParts: [BodyParts.Chest], aerobic: false },
	'Pull Ups': { bodyParts: [BodyParts.Back], aerobic: false, equipment: [Equipment.PullUpBar] },
	'Wide Grip Pull Ups': { bodyParts: [BodyParts.Back], aerobic: false, equipment: [Equipment.PullUpBar] },
	'Side to Side Wide Grip Pull Ups': { bodyParts: [BodyParts.Back], aerobic: false, equipment: [Equipment.PullUpBar] },
	'Chin Ups': { bodyParts: [BodyParts.Back, BodyParts.Biceps], aerobic: false, equipment: [Equipment.PullUpBar] },
	'Neutral Grip Pull Ups': { bodyParts: [BodyParts.Back], aerobic: false, equipment: [Equipment.PullUpBar] },
	Hang: { bodyParts: [BodyParts.Back], aerobic: false, equipment: [Equipment.PullUpBar] },
	'Scapula Pull Ups': { bodyParts: [BodyParts.Back], aerobic: false, equipment: [Equipment.PullUpBar] },
	Squats: { bodyParts: [BodyParts.Legs], aerobic: true },
	'Walking Lunges': { bodyParts: [BodyParts.Legs], aerobic: true },
	'Forward Lunges': { bodyParts: [BodyParts.Legs], aerobic: true },
	'Side Lunges': { bodyParts: [BodyParts.Legs], aerobic: true },
	'Sumo Squats': { bodyParts: [BodyParts.Legs], aerobic: true },
	'One Legged Squats': { bodyParts: [BodyParts.Legs], aerobic: true },
	'Deadmill Runs': { bodyParts: [BodyParts.Legs], aerobic: true, equipment: [Equipment.Treadmill] },
	'Jump Squats': { bodyParts: [BodyParts.Legs], aerobic: true },
	'Jumping Lunges': { bodyParts: [BodyParts.Legs], aerobic: true },
	'Wall Sit': { bodyParts: [BodyParts.Legs], aerobic: false },
	'Hamstring Hip Raise': { bodyParts: [BodyParts.Legs], aerobic: false },
	'Handstand Push Ups': { bodyParts: [BodyParts.Shoulders], aerobic: false },
	'Handstand Hold': { bodyParts: [BodyParts.Shoulders], aerobic: false },
	'Shoulder Push Ups': { bodyParts: [BodyParts.Shoulders], aerobic: false },
	'Arm Circles': { bodyParts: [BodyParts.Shoulders], aerobic: false },
	'On The Wall': { bodyParts: [BodyParts.Shoulders], aerobic: false },
	'Elbows In Push Ups': { bodyParts: [BodyParts.Triceps, BodyParts.Chest], aerobic: false },
	Burpees: { bodyParts: [BodyParts.FullBody], aerobic: true },
	'Jumping Jacks': { bodyParts: [BodyParts.FullBody], aerobic: true },
	'In And Outs': { bodyParts: [BodyParts.FullBody], aerobic: true },
	'Jump Rope': { bodyParts: [BodyParts.FullBody], aerobic: true },
	'Broad Jumps': { bodyParts: [BodyParts.FullBody], aerobic: true },
};
